import type { Metadata } from "next";
import { Footer, Navbar } from "@/components/common";

import "./globals.css";
import Providers from "./Providers";
import { AuthContextProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Edu House",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden h-screen flex flex-col">
        <Providers attribute="class" defaultTheme="system">
          <AuthContextProvider>
            <Navbar />
            <div className="pt-16 flex-grow">{children}</div>
            <Footer />
          </AuthContextProvider>
        </Providers>
      </body>
    </html>
  );
}
