import type { Metadata } from "next";
import { Footer, Navbar } from "@/components/common";
import Providers from "../Providers";

import "../globals.css";
import { UserProvider } from "@/context/UserContext";

export const metadata: Metadata = {
  title: "Edu House",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Providers attribute="class" defaultTheme="system">
        <UserProvider>
          <Navbar />
          <div className="pt-16">{children}</div>
          <Footer />
        </UserProvider>
      </Providers>
    </>
  );
}
